### ISSUE TITLE
Regarding DDP and reversible networks

### ISSUE THREAD

**Issue by Parskatt** [lucidrains/performer-pytorch#14]
Hi, I'm trying to figure out how to combine DDP with setting the network to be reversible.

My code basically looks like this:

```python
import pytorch_lightning as pl
from performer_pytorch import Performer
...
model = nn.Sequential([...,Performer(...,reversible=True)])
trainer = pl.Trainer(...
                    distributed_backend='ddp',
                    ...)
trainer.fit(model,train_loader,val_loader)
```

Now all combinations work for me (ddp/not reversible, not ddp/reversible, not ddp/not reversible) except for ddp and reversible.

The error I get is:
> RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 
>1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes
>2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases yet.

I've seen multiple people have similar issues: https://github.com/huggingface/transformers/issues/7160 ,https://github.com/pytorch/pytorch/issues/46166 , https://github.com/tatp22/linformer-pytorch/issues/23

Do you have any suggestion for how to deal with this issue? Im not really familiar with the inner workings of DDP and the autograd engine, so I'm not sure how to fix this myself.

**Comment by Parskatt** [comment]
Only thing I found was: https://github.com/pytorch/pytorch/issues/37002 , which is not in operation yet it seems.

Apex seems to have delayed allreduce implemented since before, but I'm hesitant to switch over just for this issue.

Have you run into this problem yourself, and if so did you manage to find a way around it?

**Comment by blizda** [comment]
> Only thing I found was: [pytorch/pytorch#37002](https://github.com/pytorch/pytorch/issues/37002) , which is not in operation yet it seems.
> 
> Apex seems to have delayed allreduce implemented since before, but I'm hesitant to switch over just for this issue.
> 
> Have you run into this problem yourself, and if so did you manage to find a way around it?

https://github.com/tatp22/linformer-pytorch/issues/23

**Comment by Parskatt** [comment]
@blizda Yeah I referenced that in my post. However, they solution they seemed to have was to not use checkpointing. And this defeats the purpose of having the network be reversible.

**Comment by Parskatt** [comment]
@blizda Ah, perhaps now I understand. I think it's because Im using shared parameter matrices for the embedding step perhaps. I'll look into that.

**Comment by Parskatt** [comment]
Sadly changing that back to a buffer doesnt seem to help. Maybe there is something else in the graph being called twice anyway?

**Comment by lucidrains** [comment]
@Parskatt I struggled with this many months ago with Reformer, and finally found that that using Deepspeed actually solved this issue https://github.com/lucidrains/reformer-pytorch/tree/master/examples/enwik8_deepspeed Perhaps I'll get a deepspeed example up by tonight and you can give it a try?

**Comment by lucidrains** [comment]
@Parskatt Johan -> https://github.com/lucidrains/performer-pytorch/commit/36955b055ca436c716d5494a11779368df6d6700

**Comment by lucidrains** [comment]
@Parskatt Btw, that's quite cool that you can pass in the model like that to the trainer! Does it not have to be wrapped within a LightningModule anymore?

**Comment by Parskatt** [comment]
@lucidrains Hi. Yeah I was cheating a bit, it's wrapped in a lighting module (also where my optimizer etc is defined).

I saw Deepspeed as well, Ill give it a try! (tomorrow morning here in Sweden :) )

**Comment by lucidrains** [comment]
@Parskatt haha ok, lemme know!

**Comment by Parskatt** [comment]
Yes, everything is working (I think). Reversible works without any changes using DeepSpeed.

I had to do some major refactoring of my code though... But I guess thats from bad practice on my part ;)

I'll close this for now.
