### ISSUE TITLE
Adding zeroes in softmax_kernel

### ISSUE THREAD

**Issue by marhlder** [lucidrains/performer-pytorch#17]
https://github.com/lucidrains/performer-pytorch/blob/681aacb0bbf83e72d54d703f5235c72f4d26b8ea/performer_pytorch/performer_pytorch.py#L45

What is the point of adding zeroes here? The return shape should be exactly the same as projection_matrix right? 

Is it some kind of trick to move the tensor between devices? It seems a bit fishy.

**Comment by lucidrains** [comment]
@marhlder I transcribed that from this line https://github.com/google-research/google-research/blob/master/performer/fast_self_attention/fast_self_attention.py#L84 I'm not sure either, it doesn't seem to serve a purpose

**Comment by lucidrains** [comment]
https://github.com/lucidrains/performer-pytorch/commit/a23464e8db0a2358cdf46d4d2eb159582eb5a70a
