### ISSUE TITLE
definition of layer_drop()

### ISSUE THREAD

**Issue by shi27feng** [lucidrains/performer-pytorch#18]
Hi,
it seems that the function layer_drop(..)  used by forward(..) of the class SequentialSequence is not defined?

**Comment by lucidrains** [comment]
@shi27feng Hi Feng! I forgot to remove that, it has been cleaned up in 0.7.1 ! https://github.com/lucidrains/performer-pytorch/releases/tag/0.7.1

**Comment by shi27feng** [comment]
Thanks for the prompt reply
