### ISSUE TITLE
Is it slower than original bert when training?

### ISSUE THREAD

**Issue by yygle** [lucidrains/performer-pytorch#20]
As paper say,  i transferred weights of BERT into performer, and fine-tune it on some down-stream tasks. It seems much more slow than BERT training, besides i already installed fast transformers for CUDA. Is it common or i did something wrong?

**Comment by lucidrains** [comment]
@yygle the gains for this attention really comes at longer sequence lengths, 2048 and beyond

it isn't noticeable at shorter sequence lengths such as BERT's, which I believe is 512

**Comment by yygle** [comment]
Thanks for your response. But i think at least it should not be slower than BERT, but the reality is that Performer is much more slower than BERT when training. Is it because of the gaussian orthogonal random matrix?

**Comment by yygle** [comment]
Oops, i guess it is because that, when i use parameters of bert-base model, d=768 which is larger than l in paper(which is 512).
