### ISSUE TITLE
Feature Request: Enable generalized attention. 

### ISSUE THREAD

**Issue by Parskatt** [lucidrains/performer-pytorch#3]
In the paper a generalized form of attention is tried using relus instead of exponential functions (see figure 6 in https://arxiv.org/pdf/2009.14794.pdf), perhaps this could be used with arbitrary non-linearities (relus, softplus, gelu, etc).

**Comment by lucidrains** [comment]
@Parskatt Hey Johan! I've added it in the latest commit! Let me know if it works for you

https://github.com/lucidrains/performer-pytorch/releases/tag/0.0.8

**Comment by Parskatt** [comment]
Hey, thats awesome! I'll definitely check it out!
