### ISSUE TITLE
Causal for images

### ISSUE THREAD

**Issue by Etzelkut** [lucidrains/performer-pytorch#31]
Hello, thank you for the repo!
I have a question, you gave the example for "Plain Performer, if you are working with say images or other modalities". There, your performer parameter "causal" is set to True. Can please explain why if you can of course? Is it somehow autoregressive task?
Thanks!

**Comment by lucidrains** [comment]
it can be on or off, depending on whether you are doing encoding or decoding (generating images a la iGPT https://openai.com/blog/image-gpt/)

**Comment by Etzelkut** [comment]
Thanks for the link!
