### ISSUE TITLE
Triangular matrices ?

### ISSUE THREAD

**Issue by jeremycochoy** [lucidrains/performer-pytorch#42]
Does the current implementation provide triangular matrices (to constrain the attention always on the "left" of the sequence, both for input and encoded values) as described in the last section of the original paper?

**Comment by lucidrains** [comment]
@jeremycochoy Hi Jeremy, do you mean in the autoregressive (unidirectional) case? I only see triangular matrices being mentioned in that context

**Comment by lucidrains** [comment]
@jeremycochoy can you point me at this passage in the paper?

**Comment by jeremycochoy** [comment]
Yes, its page 17, Annexe B.1. I don't know to which extends it is complex to implement this, if not already there.

**Comment by lucidrains** [comment]
@jeremycochoy ohh I see, yeah, that is for the unidirectional case, and it is already taken care of, through a cumulative sum actually (no masking needed)

**Comment by lucidrains** [comment]
@jeremycochoy you don't need to worry about that detail, you just need to set `causal = True` and you are good to go

**Comment by lucidrains** [comment]
<img width="625" alt="Screen Shot 2020-12-07 at 11 52 53 AM" src="https://user-images.githubusercontent.com/108653/101398338-c95ab100-3882-11eb-9f70-1f4df62a260b.png">
just to make sure we are looking at the same thing lol

**Comment by jeremycochoy** [comment]
There is no words to say how happy I am to learn it, thats awesome (yes we are looking at the same thing). I can't wait to test it. :)

**Comment by lucidrains** [comment]
@jeremycochoy good timing, since @Sleepychord just caught a big bug in that part of the code loll

**Comment by Muennighoff** [comment]
> @jeremycochoy good timing, since @Sleepychord just caught and fixed a big bug in that part of the code loll

Am I understanding it correct that because of the pretty neat cumsum, we could even the run EncDec without a decoder mask & still wouldn't spoil the ground truth to the model?

**Comment by Muennighoff** [comment]
& so in practice we can construct attn masks the same way for inputs & outputs and they are treated the same way by the model? @lucidrains
