### ISSUE TITLE
why is bias true in `to_<q,k,v>`?

### ISSUE THREAD

**Issue by JamesDeAntonis** [lucidrains/performer-pytorch#63]
I am referring to [these lines](https://github.com/lucidrains/performer-pytorch/blob/main/performer_pytorch/performer_pytorch.py#L315)

For reference, [in huggingface](https://github.com/huggingface/transformers/blob/master/src/transformers/models/t5/modeling_t5.py#L318), all these projections have no bias

**Comment by lucidrains** [comment]
@JamesDeAntonis yup, i agree it usually should not have projections - but another user actually was trying to fine-tune a BERT implementation to use Performer, and there they did have bias for qkv projection 🤷‍♂️ 

I think I should probably default it to False, and allow people to turn it on. Regardless, it shouldn't hurt performance

**Comment by JamesDeAntonis** [comment]
Makes sense.  Either way, could we at least make it a parameter?  I could make the changes and submit a PR if that works for you

**Comment by lucidrains** [comment]
@JamesDeAntonis ok James! done in https://github.com/lucidrains/performer-pytorch/commit/b6c2bfdd4547bf658a310e91ffe0cb5fc0b71736

**Comment by JamesDeAntonis** [comment]
awesome!  thanks!
