### ISSUE TITLE
`to_out` bias

### ISSUE THREAD

**Issue by JamesDeAntonis** [lucidrains/performer-pytorch#65]
Hi again,

Could you make it `qkvo_bias` instead?  We would also like to not have bias for `to_out`

Thanks!

**Comment by lucidrains** [comment]
@JamesDeAntonis interesting! usually the outward projection does have bias - can you point me at the implementation where it does not, or is this some in-house architecture?

**Comment by lucidrains** [comment]
@JamesDeAntonis https://github.com/lucidrains/performer-pytorch/releases/tag/1.0.7 `attn_out_bias = False` for you and your team

**Comment by JamesDeAntonis** [comment]
thanks!
