### ISSUE TITLE
Residual Connection

### ISSUE THREAD

**Issue by jiyounglee-0523** [lucidrains/performer-pytorch#77]
Hi! 
Thank you for providing wonderful implementation of performer.

I just want to ask a one little question.
I noticed that there is no residual connection in the code, did I miss something?

Or does performer not have residual connection in the first place?

Thank you for listening to my question :)

**Comment by ChaozhongLiu** [comment]
@jiyounglee-0523 Hi there, it has been years but did you find an answer yourself? I might be too dumb and haven't  yet found the residual connection in the code. Any hint is appreciated!

**Comment by lucidrains** [comment]
@ChaozhongLiu it happens [here](https://github.com/lucidrains/performer-pytorch/blob/main/performer_pytorch/reversible.py#L138)

**Comment by ChaozhongLiu** [comment]
Ahhhhh my
Thanks!
