### ISSUE TITLE
Issue with biased estimates from QR decomposition

### ISSUE THREAD

**Issue by Parskatt** [lucidrains/performer-pytorch#8]
Hi again :)

See issue: https://github.com/google-research/google-research/issues/436 that I posted on the main repository. Using the QR incorrectly produces results with significantly higher variance. There is quite an easy fix by simply doing
```python
 q, r = torch.qr(flattened)
 # Make Q uniform according to https://arxiv.org/pdf/math-ph/0609050.pdf
 d = torch.diag(r, 0)
 ph = d.sign()
 q *= ph
```

**Comment by lucidrains** [comment]
@Parskatt i'll take your word for it :) this can now be turned on with the `qr_uniform_q = True` in the constructor

i'll keep an eye on that issue in the repo, and if the authors go ahead with it, i'll remove the option and default it on

**Comment by lucidrains** [comment]
@Parskatt have you run any experiments with this potential fix?

**Comment by Parskatt** [comment]
Im working more on the theoretical side at the moment. I just realised when I generated these matrices that I got a biased estimate (in 2d i literally got no samples in the 4th quadrant but maybe that was someting wrong on my end). Anyway, for those experiments I reduced the variance with about ~50%.

In the experiments Im running myself im still using learnable matrices.

**Comment by lucidrains** [comment]
How do the learned matrices perform??

**Comment by lucidrains** [comment]
@Parskatt haha yea, its hard to imagine someone hasn't tried it already, but just curious :D

**Comment by Parskatt** [comment]
@lucidrains I concluded the thread over at google-research. Summary seems to be, yes it is theoretically better to use the flipped version, but it probably doesnt really matter if the dimensionality is large :)

**Comment by Parskatt** [comment]
Basically I dont think you have to implement it, especially if you want it to be comparable to the original implementation, but it wouldn't hurt either. You can close this issue unless there is something more you want to discuss :)

**Comment by lucidrains** [comment]
@Parskatt i already have it built, and will keep it hidden behind a keyword argument flag :) do feel to reopen if you were able to show that it makes a difference on downstream tasks!
