### ISSUE TITLE
Suggestion: Renormalization step for linear attention

### ISSUE THREAD

**Issue by Parskatt** [lucidrains/performer-pytorch#9]
When I used generalized attention without normalizing the the attention matrix I got some crazy big losses (because norms explode inside the network). Now I'm using a renormalization step (basically computing D^-1 as described in the paper):
```python
def linear_attention(q, k, v,renormalize=True):
    Dinv = 1.0/torch.einsum('...nd,...d -> ...n',q,torch.einsum('...nd->...d',k))
    context = torch.einsum('...nd,...ne->...de', k, v)
    out = torch.einsum('...de,...nd->...ne', context, q)
    out = torch.einsum('...n,...ne->...ne',Dinv,out)
    return out
```
To renormalize. Obviously my code is stupidly written (not using the kwarg at all), but I think its a nice feature.
I might have messed up the dimensions and stuff here, so please tell me if something doesnt make sense ;)

**Comment by Parskatt** [comment]
I have no idea how to compute this is the attention matrix contains negative values though...

**Comment by lucidrains** [comment]
@Parskatt Thank you Johan! Indeed I checked the paper and this is always used in the paper, so I turned it on by default. I think we have to assume the kernel functions being passed in results in positive matrices
